# Generated by Django 5.2.8 on 2025-12-11 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PunctDeInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_pct', models.CharField(max_length=150)),
                ('tip_pct', models.CharField(choices=[('cabana', 'Cabana'), ('lac', 'Lac'), ('cascada', 'Cascada'), ('varf', 'Varf'), ('refugiu', 'Refugiu')], max_length=10)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('latitudine', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitudine', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='puncte_interes/')),
            ],
            options={
                'verbose_name_plural': 'Puncte de Interes',
            },
        ),
        migrations.CreateModel(
            name='ZonaMontana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_zona', models.CharField(max_length=100, unique=True)),
                ('regiune', models.CharField(blank=True, max_length=100, null=True)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('imagine_reprezentativa', models.ImageField(blank=True, null=True, upload_to='zone_montane/')),
            ],
            options={
                'verbose_name_plural': 'Zone Montane',
            },
        ),
        migrations.CreateModel(
            name='Marcaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('banda', 'Banda'), ('cruce', 'Cruce'), ('triunghi', 'Triunghi'), ('punct', 'Punct/Cerc')], max_length=10)),
                ('culoare', models.CharField(choices=[('rosu', 'Rosu'), ('galben', 'Galben'), ('albastru', 'Albastru')], max_length=10)),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='marcaje_icons/')),
            ],
            options={
                'verbose_name_plural': 'Marcaje',
                'unique_together': {('tip', 'culoare')},
            },
        ),
        migrations.CreateModel(
            name='Traseu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_traseu', models.CharField(max_length=150)),
                ('dificultate', models.CharField(choices=[('usor', 'Usor'), ('mediu', 'Mediu'), ('dificil', 'Dificil'), ('expert', 'Expert')], max_length=10)),
                ('durata_traseu', models.DecimalField(decimal_places=1, max_digits=4)),
                ('distanta_km', models.DecimalField(decimal_places=1, max_digits=5)),
                ('altitudine_maxima', models.IntegerField(blank=True, null=True)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('track_gpx', models.FileField(blank=True, null=True, upload_to='trasee_gpx/')),
                ('marcaje', models.ManyToManyField(related_name='trasee', to='app.marcaj')),
                ('puncte_interes', models.ManyToManyField(blank=True, to='app.punctdeinteres')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zonamontana')),
            ],
            options={
                'verbose_name_plural': 'Trasee',
            },
        ),
        migrations.CreateModel(
            name='Recenzie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluare', models.IntegerField(choices=[(1, '1 Stele'), (2, '2 Stele'), (3, '3 Stele'), (4, '4 Stele'), (5, '5 Stele')])),
                ('comentariu', models.TextField()),
                ('data_postarii', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('traseu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenzii', to='app.traseu')),
            ],
            options={
                'verbose_name_plural': 'Recenzii',
            },
        ),
        migrations.CreateModel(
            name='ImagineTraseu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagine', models.ImageField(upload_to='trasee_foto/')),
                ('descriere', models.CharField(blank=True, max_length=100, null=True)),
                ('traseu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagini', to='app.traseu')),
            ],
        ),
        migrations.AddField(
            model_name='punctdeinteres',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zonamontana'),
        ),
    ]
