# Generated by Django 5.2.8 on 2025-12-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traseu',
            name='sezon_recomandat',
            field=models.CharField(blank=True, choices=[('primavara', 'Primavara'), ('vara', 'Vara'), ('toamna', 'Toamna'), ('iarna', 'Iarna'), ('tot_timpul', 'Tot timpul')], max_length=20, null=True),
        ),
    ]
